# Generated by Django 5.1.4 on 2024-12-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='date',
        ),
        migrations.RemoveField(
            model_name='community',
            name='free',
        ),
        migrations.RemoveField(
            model_name='community',
            name='name',
        ),
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(default='Без названия', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(),
        ),
    ]
